# Generated by Django 3.2.15 on 2022-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('amount', models.IntegerField(db_column='Amount')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
