# Generated by Django 3.2.15 on 2022-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_id', models.IntegerField()),
                ('quantity', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
